---
- name: Install Apache web server
  package:
    name: apache2
    state: present

- name: Enable and start Apache
  service:
    name: apache2
    enabled: yes
    state: started

- name: Install web files
  copy:
    src: ./files/index.html
    dest: /var/www/html/index.html
    mode: '644'
    owner: 'root'
    group: 'root'
